// <auto-generated />
namespace SimpleMembershipPrac.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedthetestpropertytocategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedthetestpropertytocategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201902152249471_addedthetestpropertytocategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
